dist: bionic
language: c
compiler:
  - gcc

env:
  - SCAN_BUILD="scan-build --status-bugs" CFLAGS="-g -O2" CHECK=0
  - CFLAGS="-fsanitize=address -g -O2" LDFLAGS="-lasan" CHECK=1

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clang cppcheck freeradius libgnutls28-dev libasan0
  - touch config.rpath && autoreconf -fvi

script:
  - CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" $SCAN_BUILD ./configure --with-tls
  - $SCAN_BUILD make -j $(nproc)
  - if test $CHECK = 1;then
      sudo make check &&
      touch doc/stamp_mans &&
      make ABI_SKIP=1 dist;
    fi

after_script:
  - cppcheck --force -q -Iinclude lib src

after_failure:
  - cat tests/test-suite.log
